package services

import (
	"fmt"
	"sync"
	"time"

	"netsentinel-x-backend/models"
)

type IncidentService struct {
	mu        sync.RWMutex
	incidents map[string]models.Incident
}

func NewIncidentService() *IncidentService {
	s := &IncidentService{
		incidents: make(map[string]models.Incident),
	}
	s.seedIncidentData()
	return s
}

func (s *IncidentService) seedIncidentData() {
	now := time.Now()

	inc1 := models.Incident{
		ID:                    "INC-2026-8001",
		Title:                 "Automated C2 Beaconing & Data Exfiltration Event",
		Summary:               "Host 192.168.1.105 demonstrated strict periodic HTTPS C2 beaconing coupled with high-volume outbound data transfers to untrusted external IP 198.51.100.45.",
		Severity:              "CRITICAL",
		Priority:              "P1",
		Status:                "INVESTIGATING",
		AssignedAnalyst:       "Lead SOC Engineer (Ayush)",
		AssignedRole:          "Incident Commander",
		CreatedAt:             now.Add(-45 * time.Minute),
		UpdatedAt:             now.Add(-5 * time.Minute),
		DueDate:               now.Add(15 * time.Minute),
		AffectedAssets:        []string{"192.168.1.105 (Workstation-A)", "Internal VLAN-10"},
		RelatedAlerts:         []string{"ALT-8001: Suspicious Beaconing", "ALT-8004: Large Outbound Transfer"},
		RelatedInvestigations: []string{"INV-2026-001"},
		RelatedIOCs:           []string{"198.51.100.45"},
		MITRETechniques:       []string{"T1071.001 - Web Protocols", "T1041 - Exfiltration Over C2 Channel"},
		Timeline: []models.IncidentTimelineEntry{
			{
				ID:         "TL-001",
				IncidentID: "INC-2026-8001",
				Timestamp:  now.Add(-45 * time.Minute),
				Activity:   "Detection Triggered",
				Category:   "ALERT",
				Actor:      "Detection Engine",
				Details:    "High-entropy DNS beaconing alert generated by Rule RULE-SIGMA-001.",
			},
			{
				ID:         "TL-002",
				IncidentID: "INC-2026-8001",
				Timestamp:  now.Add(-40 * time.Minute),
				Activity:   "Threat Intel Enriched",
				Category:   "ENRICHMENT",
				Actor:      "Intel Fusion Service",
				Details:    "IP 198.51.100.45 scored 88/100 risk on VirusTotal & AbuseIPDB.",
			},
			{
				ID:         "TL-003",
				IncidentID: "INC-2026-8001",
				Timestamp:  now.Add(-35 * time.Minute),
				Activity:   "Incident Promoted & Assigned",
				Category:   "TRIAGE",
				Actor:      "SOC Manager",
				Details:    "Promoted alert to CRITICAL P1 incident and assigned to Lead SOC Engineer.",
			},
		},
		Evidence: []models.IncidentEvidence{
			{
				ID:            "EVD-001",
				IncidentID:    "INC-2026-8001",
				Timestamp:     now.Add(-44 * time.Minute),
				Source:        "Packet DPI Dissector",
				Type:          "PACKET",
				Title:         "60s Outbound TLS Handshake Log",
				Content:       "Client Hello SNI: c2-command.malicious.net | Dest Port: 443 | Payload Size: 4096 bytes",
				RelatedEntity: "192.168.1.105",
				Confidence:    0.98,
			},
			{
				ID:            "EVD-002",
				IncidentID:    "INC-2026-8001",
				Timestamp:     now.Add(-38 * time.Minute),
				Source:        "UEBA Engine",
				Type:          "REPORT",
				Title:         "UEBA Anomaly Report ANOM-2026-001",
				Content:       "+480% connection rate departure from 30-day baseline.",
				RelatedEntity: "192.168.1.105",
				Confidence:    0.95,
			},
		},
		ResolutionNotes: "",
		SLA: models.SLARecord{
			IncidentID:              "INC-2026-8001",
			TargetResponseTimeMin:   15,
			TargetResolutionTimeMin: 60,
			ActualResponseTimeMin:   10,
			ActualResolutionTimeMin: 0,
			SLAStatus:               "ON_TRACK",
			RemainingMinutes:        15,
		},
	}

	inc2 := models.Incident{
		ID:                    "INC-2026-8002",
		Title:                 "SSH Authentication Brute Force Sequence",
		Summary:               "Repeated failed SSH logins targeting DB-Primary server from external subnet.",
		Severity:              "HIGH",
		Priority:              "P2",
		Status:                "TRIAGED",
		AssignedAnalyst:       "Tier-2 SOC Analyst",
		AssignedRole:          "Analyst",
		CreatedAt:             now.Add(-120 * time.Minute),
		UpdatedAt:             now.Add(-60 * time.Minute),
		DueDate:               now.Add(120 * time.Minute),
		AffectedAssets:        []string{"192.168.1.180 (DB-Primary)"},
		RelatedAlerts:         []string{"ALT-8002: SSH Brute Force"},
		RelatedInvestigations: []string{},
		RelatedIOCs:           []string{"203.0.113.88"},
		MITRETechniques:       []string{"T1110.001 - Password Guessing"},
		Timeline: []models.IncidentTimelineEntry{
			{
				ID:         "TL-101",
				IncidentID: "INC-2026-8002",
				Timestamp:  now.Add(-120 * time.Minute),
				Activity:   "Alert Triggered",
				Category:   "ALERT",
				Actor:      "Detection Engine",
				Details:    "50 failed SSH authentication attempts in 10 seconds.",
			},
		},
		Evidence: []models.IncidentEvidence{
			{
				ID:            "EVD-101",
				IncidentID:    "INC-2026-8002",
				Timestamp:     now.Add(-119 * time.Minute),
				Source:        "Auth Log",
				Type:          "LOG",
				Title:         "SSHD Auth Failures",
				Content:       "Failed password for root from 203.0.113.88 port 54321 ssh2",
				RelatedEntity: "192.168.1.180",
				Confidence:    0.90,
			},
		},
		ResolutionNotes: "",
		SLA: models.SLARecord{
			IncidentID:              "INC-2026-8002",
			TargetResponseTimeMin:   30,
			TargetResolutionTimeMin: 180,
			ActualResponseTimeMin:   15,
			ActualResolutionTimeMin: 0,
			SLAStatus:               "ON_TRACK",
			RemainingMinutes:        120,
		},
	}

	s.incidents[inc1.ID] = inc1
	s.incidents[inc2.ID] = inc2
}

func (s *IncidentService) GetOverview() models.IncidentOverview {
	s.mu.RLock()
	defer s.mu.RUnlock()

	openCount := 0
	critCount := 0
	slaBreaches := 0
	statusDist := map[string]int{
		"NEW": 0, "TRIAGED": 0, "INVESTIGATING": 0, "CONTAINMENT": 0,
		"ERADICATION": 0, "RECOVERY": 0, "CLOSED": 0,
	}

	var recents []models.Incident
	for _, inc := range s.incidents {
		statusDist[inc.Status]++
		if inc.Status != "CLOSED" {
			openCount++
		}
		if inc.Severity == "CRITICAL" {
			critCount++
		}
		if inc.SLA.SLAStatus == "BREACHED" {
			slaBreaches++
		}
		recents = append(recents, inc)
	}

	return models.IncidentOverview{
		TotalIncidents:    len(s.incidents),
		OpenIncidents:     openCount,
		CriticalIncidents: critCount,
		SLABreachCount:    slaBreaches,
		AvgMTTRMinutes:    38,
		IncidentsByStatus: statusDist,
		RecentIncidents:   recents,
	}
}

func (s *IncidentService) GetIncidents() []models.Incident {
	s.mu.RLock()
	defer s.mu.RUnlock()

	var list []models.Incident
	for _, inc := range s.incidents {
		list = append(list, inc)
	}
	return list
}

func (s *IncidentService) GetIncidentByID(id string) (models.Incident, bool) {
	s.mu.RLock()
	defer s.mu.RUnlock()

	inc, exists := s.incidents[id]
	return inc, exists
}

func (s *IncidentService) CreateIncident(title, summary, severity, priority, analyst string, assets []string) models.Incident {
	s.mu.Lock()
	defer s.mu.Unlock()

	now := time.Now()
	incID := fmt.Sprintf("INC-2026-%d", now.Unix()%10000)

	targetResp := 30
	targetRes := 180
	if severity == "CRITICAL" || priority == "P1" {
		targetResp = 15
		targetRes = 60
	}

	inc := models.Incident{
		ID:              incID,
		Title:           title,
		Summary:         summary,
		Severity:        severity,
		Priority:        priority,
		Status:          "NEW",
		AssignedAnalyst: analyst,
		AssignedRole:    "Incident Commander",
		CreatedAt:       now,
		UpdatedAt:       now,
		DueDate:         now.Add(time.Duration(targetRes) * time.Minute),
		AffectedAssets:  assets,
		Timeline: []models.IncidentTimelineEntry{
			{
				ID:         fmt.Sprintf("TL-%d", now.Unix()%1000),
				IncidentID: incID,
				Timestamp:  now,
				Activity:   "Incident Created",
				Category:   "CREATION",
				Actor:      analyst,
				Details:    fmt.Sprintf("Incident created with severity %s", severity),
			},
		},
		Evidence: make([]models.IncidentEvidence, 0),
		SLA: models.SLARecord{
			IncidentID:              incID,
			TargetResponseTimeMin:   targetResp,
			TargetResolutionTimeMin: targetRes,
			SLAStatus:               "ON_TRACK",
			RemainingMinutes:        targetRes,
		},
	}

	s.incidents[incID] = inc
	return inc
}

func (s *IncidentService) AddEvidence(incID, source, evType, title, content, entity string) (models.IncidentEvidence, bool) {
	s.mu.Lock()
	defer s.mu.Unlock()

	inc, exists := s.incidents[incID]
	if !exists {
		return models.IncidentEvidence{}, false
	}

	now := time.Now()
	ev := models.IncidentEvidence{
		ID:            fmt.Sprintf("EVD-%d", now.Unix()%10000),
		IncidentID:    incID,
		Timestamp:     now,
		Source:        source,
		Type:          evType,
		Title:         title,
		Content:       content,
		RelatedEntity: entity,
		Confidence:    0.95,
	}

	inc.Evidence = append(inc.Evidence, ev)
	inc.UpdatedAt = now
	s.incidents[incID] = inc

	return ev, true
}

func (s *IncidentService) AssignAnalyst(incID, analyst, role string) bool {
	s.mu.Lock()
	defer s.mu.Unlock()

	inc, exists := s.incidents[incID]
	if !exists {
		return false
	}

	now := time.Now()
	inc.AssignedAnalyst = analyst
	inc.AssignedRole = role
	if inc.Status == "NEW" {
		inc.Status = "TRIAGED"
	}
	inc.UpdatedAt = now

	inc.Timeline = append(inc.Timeline, models.IncidentTimelineEntry{
		ID:         fmt.Sprintf("TL-%d", now.Unix()%1000),
		IncidentID: incID,
		Timestamp:  now,
		Activity:   "Analyst Assigned",
		Category:   "ASSIGNMENT",
		Actor:      "SOC Operations",
		Details:    fmt.Sprintf("Assigned to %s as %s", analyst, role),
	})

	s.incidents[incID] = inc
	return true
}

func (s *IncidentService) CloseIncident(incID, notes string) bool {
	s.mu.Lock()
	defer s.mu.Unlock()

	inc, exists := s.incidents[incID]
	if !exists {
		return false
	}

	now := time.Now()
	inc.Status = "CLOSED"
	inc.ResolutionNotes = notes
	inc.UpdatedAt = now

	inc.Timeline = append(inc.Timeline, models.IncidentTimelineEntry{
		ID:         fmt.Sprintf("TL-%d", now.Unix()%1000),
		IncidentID: incID,
		Timestamp:  now,
		Activity:   "Incident Closed",
		Category:   "RESOLUTION",
		Actor:      inc.AssignedAnalyst,
		Details:    fmt.Sprintf("Closed with resolution: %s", notes),
	})

	s.incidents[incID] = inc
	return true
}
