
services:

  postgres:
    image: postgres:17
    container_name: netsentinel-postgres

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Sandy
      POSTGRES_DB: netsentinelx

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: netsentinel-backend

    depends_on:
      - postgres

    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    container_name: netsentinel-frontend

    depends_on:
      - backend

    ports:
      - "3000:3000"

volumes:
  postgres_data: