"use client";

import React, { useState, useEffect, useCallback } from "react";
import {
  ShieldAlert,
  Clock,
  CheckCircle2,
  FileText,
  Plus,
  ChevronRight,
  Sparkles,
  X
} from "lucide-react";

export interface IncidentTimelineEntry {
  id: string;
  incident_id: string;
  timestamp: string;
  activity: string;
  category: string;
  actor: string;
  details: string;
}

export interface IncidentEvidence {
  id: string;
  incident_id: string;
  timestamp: string;
  source: string;
  type: string;
  title: string;
  content: string;
  related_entity: string;
  confidence: number;
}

export interface SLARecord {
  incident_id: string;
  target_response_time_min: number;
  target_resolution_time_min: number;
  actual_response_time_min: number;
  actual_resolution_time_min: number;
  sla_status: string;
  remaining_minutes: number;
}

export interface Incident {
  id: string;
  title: string;
  summary: string;
  severity: string;
  priority: string;
  status: string;
  assigned_analyst: string;
  assigned_role: string;
  created_at: string;
  updated_at: string;
  due_date: string;
  affected_assets: string[];
  related_alerts: string[];
  related_investigations: string[];
  related_iocs: string[];
  mitre_techniques: string[];
  timeline: IncidentTimelineEntry[];
  evidence: IncidentEvidence[];
  resolution_notes: string;
  sla: SLARecord;
}

export interface IncidentOverview {
  total_incidents: number;
  open_incidents: number;
  critical_incidents: number;
  sla_breach_count: number;
  avg_mttr_minutes: number;
  incidents_by_status: Record<string, number>;
  recent_incidents: Incident[];
}

export default function AIIncidentDesk() {
  const [overview, setOverview] = useState<IncidentOverview | null>(null);
  const [incidents, setIncidents] = useState<Incident[]>([]);
  const [selectedIncident, setSelectedIncident] = useState<Incident | null>(null);
  const [activeTab, setActiveTab] = useState<"queue" | "inspector">("queue");

  // Create Incident Modal State
  const [showCreateModal, setShowCreateModal] = useState(false);
  const [newTitle, setNewTitle] = useState("");
  const [newSummary, setNewSummary] = useState("");
  const [newSeverity, setNewSeverity] = useState("HIGH");
  const [newAnalyst, setNewAnalyst] = useState("Lead SOC Engineer");

  // Close Modal State
  const [showCloseModal, setShowCloseModal] = useState(false);
  const [resolutionNotes, setResolutionNotes] = useState("");

  const fetchIncidentData = useCallback(async () => {
    try {
      const apiUrl = process.env.NEXT_PUBLIC_API_URL || "http://localhost:8080";
      const [overRes, incRes] = await Promise.all([
        fetch(`${apiUrl}/api/v2/incidents`),
        fetch(`${apiUrl}/api/v2/incidents/list`),
      ]);

      if (overRes.ok) {
        const data = await overRes.json();
        setOverview(data);
      }
      if (incRes.ok) {
        const data = await incRes.json();
        const list = data.incidents || [];
        setIncidents(list);
        if (list.length > 0) {
          setSelectedIncident(list[0]);
        }
      }
    } catch (err) {
      console.error("Failed to fetch incident data:", err);
      const mockIncidents: Incident[] = [
        {
          id: "INC-2026-8001",
          title: "Automated C2 Beaconing & Data Exfiltration Event",
          summary: "Host 192.168.1.105 demonstrated strict periodic HTTPS C2 beaconing coupled with high-volume outbound data transfers.",
          severity: "CRITICAL",
          priority: "P1",
          status: "INVESTIGATING",
          assigned_analyst: "Lead SOC Engineer (Ayush)",
          assigned_role: "Incident Commander",
          created_at: new Date().toISOString(),
          updated_at: new Date().toISOString(),
          due_date: new Date(Date.now() + 15 * 60000).toISOString(),
          affected_assets: ["192.168.1.105 (Workstation-A)"],
          related_alerts: ["ALT-8001: Suspicious Beaconing"],
          related_investigations: ["INV-2026-001"],
          related_iocs: ["198.51.100.45"],
          mitre_techniques: ["T1071.001 - Web Protocols"],
          timeline: [
            {
              id: "TL-001",
              incident_id: "INC-2026-8001",
              timestamp: new Date().toISOString(),
              activity: "Detection Triggered",
              category: "ALERT",
              actor: "Detection Engine",
              details: "High-entropy DNS beaconing alert generated by Rule RULE-SIGMA-001.",
            },
          ],
          evidence: [
            {
              id: "EVD-001",
              incident_id: "INC-2026-8001",
              timestamp: new Date().toISOString(),
              source: "Packet DPI Dissector",
              type: "PACKET",
              title: "60s Outbound TLS Handshake Log",
              content: "Client Hello SNI: c2-command.malicious.net | Dest Port: 443",
              related_entity: "192.168.1.105",
              confidence: 0.98,
            },
          ],
          resolution_notes: "",
          sla: {
            incident_id: "INC-2026-8001",
            target_response_time_min: 15,
            target_resolution_time_min: 60,
            actual_response_time_min: 10,
            actual_resolution_time_min: 0,
            sla_status: "ON_TRACK",
            remaining_minutes: 15,
          },
        },
      ];

      setOverview({
        total_incidents: 1,
        open_incidents: 1,
        critical_incidents: 1,
        sla_breach_count: 0,
        avg_mttr_minutes: 38,
        incidents_by_status: { INVESTIGATING: 1 },
        recent_incidents: mockIncidents,
      });
      setIncidents(mockIncidents);
      setSelectedIncident(mockIncidents[0]);
    }
  }, []);

  useEffect(() => {
    const timer = setTimeout(() => {
      void fetchIncidentData();
    }, 0);
    return () => clearTimeout(timer);
  }, [fetchIncidentData]);

  const handleCreateIncident = async (e: React.FormEvent) => {
    e.preventDefault();
    try {
      const apiUrl = process.env.NEXT_PUBLIC_API_URL || "http://localhost:8080";
      const res = await fetch(`${apiUrl}/api/v2/incidents/create`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          title: newTitle,
          summary: newSummary,
          severity: newSeverity,
          priority: newSeverity === "CRITICAL" ? "P1" : "P2",
          analyst: newAnalyst,
          affected_assets: ["Internal VLAN-10"],
        }),
      });

      if (res.ok) {
        setShowCreateModal(false);
        setNewTitle("");
        setNewSummary("");
        void fetchIncidentData();
      }
    } catch (err) {
      console.error("Create incident failed:", err);
    }
  };

  const handleCloseIncident = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!selectedIncident) return;

    try {
      const apiUrl = process.env.NEXT_PUBLIC_API_URL || "http://localhost:8080";
      const res = await fetch(`${apiUrl}/api/v2/incidents/${selectedIncident.id}/close`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          resolution_notes: resolutionNotes,
        }),
      });

      if (res.ok) {
        setShowCloseModal(false);
        setResolutionNotes("");
        void fetchIncidentData();
      }
    } catch (err) {
      console.error("Close incident failed:", err);
    }
  };

  return (
    <div className="bg-zinc-950 border border-rose-500/40 rounded-2xl p-6 shadow-2xl text-white font-sans space-y-6">
      
      {/* Module Header */}
      <div className="flex flex-col lg:flex-row lg:items-center justify-between gap-4 border-b border-zinc-800 pb-5">
        <div className="flex items-center gap-3">
          <div className="p-3 rounded-xl bg-rose-950/80 border border-rose-500/50 text-rose-400 shadow-[0_0_20px_rgba(244,63,94,0.25)]">
            <ShieldAlert className="w-6 h-6" />
          </div>
          <div>
            <h2 className="text-xl font-bold text-white flex items-center gap-2">
              AI Incident Management Desk
              <span className="text-xs px-2 py-0.5 rounded bg-rose-950 text-rose-300 border border-rose-800 font-mono">
                SLA &amp; Lifecycle Desk v2.0
              </span>
            </h2>
            <p className="text-xs text-zinc-400">End-to-End SOC Incident Lifecycle, Evidence Locker &amp; Response SLA Tracking</p>
          </div>
        </div>

        {/* Tab Selector & Action CTA */}
        <div className="flex items-center gap-2 font-mono text-xs">
          <div className="flex items-center p-1 bg-zinc-900 rounded-xl border border-zinc-800">
            <button
              onClick={() => setActiveTab("queue")}
              className={`px-3 py-1.5 rounded-lg transition-colors flex items-center gap-1.5 ${
                activeTab === "queue"
                  ? "bg-rose-950 text-rose-300 border border-rose-800"
                  : "text-zinc-400 hover:text-white"
              }`}
            >
              <FileText className="w-3.5 h-3.5" />
              <span>Incident Queue</span>
            </button>
            <button
              onClick={() => setActiveTab("inspector")}
              className={`px-3 py-1.5 rounded-lg transition-colors flex items-center gap-1.5 ${
                activeTab === "inspector"
                  ? "bg-rose-950 text-rose-300 border border-rose-800"
                  : "text-zinc-400 hover:text-white"
              }`}
            >
              <Clock className="w-3.5 h-3.5 text-rose-400" />
              <span>Case Inspector</span>
            </button>
          </div>

          <button
            onClick={() => setShowCreateModal(true)}
            className="px-3.5 py-2 rounded-xl bg-rose-600 hover:bg-rose-500 text-white font-bold shadow-[0_0_15px_rgba(244,63,94,0.4)] transition-all active:scale-95 flex items-center gap-1.5"
          >
            <Plus className="w-4 h-4" />
            <span>New Incident</span>
          </button>
        </div>
      </div>

      {/* Incident Overview Analytics Banner */}
      {overview && (
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 bg-zinc-900/60 p-4 rounded-xl border border-zinc-800 text-xs font-mono">
          <div>
            <span className="text-zinc-400 text-[10px] block uppercase">Total Incidents</span>
            <span className="text-lg font-bold text-rose-400">{overview.total_incidents} Cases</span>
          </div>
          <div>
            <span className="text-zinc-400 text-[10px] block uppercase">Open &amp; Active</span>
            <span className="text-lg font-bold text-amber-400">{overview.open_incidents} Active</span>
          </div>
          <div>
            <span className="text-zinc-400 text-[10px] block uppercase">Critical P1 Incidents</span>
            <span className="text-lg font-bold text-red-500">{overview.critical_incidents} Critical</span>
          </div>
          <div>
            <span className="text-zinc-400 text-[10px] block uppercase">Avg MTTR SLA</span>
            <span className="text-lg font-bold text-emerald-400">{overview.avg_mttr_minutes} Minutes</span>
          </div>
        </div>
      )}

      {/* Main Tab View */}
      {activeTab === "queue" ? (
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 font-sans text-xs">
          
          {/* Incident Queue Table */}
          <div className="lg:col-span-2 bg-zinc-900/80 rounded-2xl border border-zinc-800 overflow-hidden shadow-lg">
            <div className="p-4 border-b border-zinc-800 flex items-center justify-between font-mono text-zinc-400">
              <span>ACTIVE INCIDENT WORK QUEUE</span>
              <span>SLA STATUS</span>
            </div>

            <div className="divide-y divide-zinc-800">
              {incidents.map((inc) => (
                <div
                  key={inc.id}
                  onClick={() => {
                    setSelectedIncident(inc);
                    setActiveTab("inspector");
                  }}
                  className={`p-4 flex items-center justify-between cursor-pointer transition-colors ${
                    selectedIncident?.id === inc.id ? "bg-rose-950/30 border-l-4 border-rose-500" : "hover:bg-zinc-900/50"
                  }`}
                >
                  <div className="space-y-1">
                    <div className="flex items-center gap-2 font-mono">
                      <span className="font-bold text-white text-sm">{inc.id} — {inc.title}</span>
                      <span
                        className={`text-[10px] font-bold px-2 py-0.5 rounded ${
                          inc.severity === "CRITICAL"
                            ? "bg-red-950 text-red-300 border border-red-800"
                            : "bg-amber-950 text-amber-300 border border-amber-800"
                        }`}
                      >
                        {inc.severity} ({inc.priority})
                      </span>
                    </div>
                    <p className="text-zinc-400 text-xs font-mono">
                      Status: {inc.status} • Analyst: {inc.assigned_analyst} • Evidence: {inc.evidence?.length || 0}
                    </p>
                  </div>

                  <div className="flex items-center gap-3 font-mono">
                    <div className="text-right">
                      <span className="text-sm font-bold text-emerald-400 block">{inc.sla?.sla_status || "ON_TRACK"}</span>
                      <span className="text-[9px] text-zinc-500 block uppercase">SLA REMAINING</span>
                    </div>
                    <ChevronRight className="w-4 h-4 text-zinc-600" />
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* Quick Action Preview Card */}
          {selectedIncident ? (
            <div className="bg-zinc-900/80 p-5 rounded-2xl border border-zinc-800 space-y-4 font-mono">
              <div className="border-b border-zinc-800 pb-3">
                <span className="text-[10px] text-zinc-400 block uppercase">Selected Incident Case</span>
                <h4 className="text-base font-bold text-white font-sans pt-1">{selectedIncident.id}</h4>
              </div>

              <div className="space-y-2 text-xs">
                <div className="flex justify-between p-2.5 bg-black rounded-lg border border-zinc-800">
                  <span className="text-zinc-400">Status:</span>
                  <span className="text-rose-400 font-bold">{selectedIncident.status}</span>
                </div>
                <div className="flex justify-between p-2.5 bg-black rounded-lg border border-zinc-800">
                  <span className="text-zinc-400">Analyst:</span>
                  <span className="text-cyan-400 font-bold">{selectedIncident.assigned_analyst}</span>
                </div>
                <div className="flex justify-between p-2.5 bg-black rounded-lg border border-zinc-800">
                  <span className="text-zinc-400">Assets:</span>
                  <span className="text-amber-400 font-bold">{selectedIncident.affected_assets?.join(", ") || "None"}</span>
                </div>
              </div>

              <div className="space-y-2 bg-rose-950/20 border border-rose-900/40 p-4 rounded-xl">
                <span className="text-xs font-bold text-rose-400 flex items-center gap-1.5 font-mono">
                  <Sparkles className="w-4 h-4" />
                  <span>AI Summary:</span>
                </span>
                <p className="text-xs text-zinc-200 leading-relaxed font-sans">
                  {selectedIncident.summary}
                </p>
              </div>

              <button
                onClick={() => setShowCloseModal(true)}
                className="w-full py-2.5 rounded-xl bg-emerald-600 hover:bg-emerald-500 text-black font-bold flex items-center justify-center gap-1.5 shadow-md"
              >
                <CheckCircle2 className="w-4 h-4" />
                <span>Resolve &amp; Close Incident</span>
              </button>
            </div>
          ) : null}

        </div>
      ) : (
        /* Case Inspector View */
        selectedIncident && (
          <div className="space-y-6 font-sans text-xs">
            <div className="bg-zinc-900/80 p-5 rounded-2xl border border-zinc-800 space-y-4">
              <div className="flex flex-col md:flex-row md:items-center justify-between gap-2 border-b border-zinc-800 pb-3 font-mono">
                <div>
                  <span className="text-xs text-rose-400 font-bold block">{selectedIncident.id}</span>
                  <h3 className="text-lg font-bold text-white font-sans">{selectedIncident.title}</h3>
                </div>
                <div className="flex items-center gap-2">
                  <span className="px-3 py-1 rounded bg-rose-950 text-rose-300 border border-rose-800 font-bold text-xs font-mono">
                    STATUS: {selectedIncident.status}
                  </span>
                  <span className="px-3 py-1 rounded bg-zinc-900 text-cyan-400 border border-zinc-800 font-bold text-xs font-mono">
                    SLA: {selectedIncident.sla?.sla_status}
                  </span>
                </div>
              </div>

              {/* Incident Timeline */}
              <div className="space-y-3 font-mono">
                <h4 className="text-xs font-bold text-zinc-400 uppercase tracking-wider">Chronological Incident Timeline</h4>
                <div className="space-y-2">
                  {selectedIncident.timeline?.map((tl) => (
                    <div key={tl.id} className="p-3 bg-black rounded-xl border border-zinc-800 flex items-start justify-between gap-3 text-xs">
                      <div className="space-y-1">
                        <div className="flex items-center gap-2">
                          <span className="text-rose-400 font-bold">[{tl.category}]</span>
                          <span className="text-white font-bold">{tl.activity}</span>
                          <span className="text-zinc-500">by {tl.actor}</span>
                        </div>
                        <p className="text-zinc-300 font-sans">{tl.details}</p>
                      </div>
                      <span className="text-[10px] text-zinc-500 whitespace-nowrap">{new Date(tl.timestamp).toLocaleTimeString()}</span>
                    </div>
                  ))}
                </div>
              </div>

              {/* Evidence Locker */}
              <div className="space-y-3 font-mono pt-2">
                <h4 className="text-xs font-bold text-zinc-400 uppercase tracking-wider">Evidence Locker ({selectedIncident.evidence?.length || 0})</h4>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                  {selectedIncident.evidence?.map((ev) => (
                    <div key={ev.id} className="p-3.5 bg-black rounded-xl border border-zinc-800 space-y-1.5">
                      <div className="flex items-center justify-between">
                        <span className="text-cyan-400 font-bold text-xs">{ev.title}</span>
                        <span className="text-[10px] px-2 py-0.5 rounded bg-zinc-900 text-zinc-400 border border-zinc-800">{ev.type}</span>
                      </div>
                      <p className="text-zinc-300 font-sans text-xs">{ev.content}</p>
                      <span className="text-[10px] text-emerald-400 block pt-1">Confidence: {Math.round(ev.confidence * 100)}%</span>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          </div>
        )
      )}

      {/* Create Incident Modal */}
      {showCreateModal && (
        <div className="fixed inset-0 bg-black/80 backdrop-blur-sm z-50 flex items-center justify-center p-4">
          <div className="bg-zinc-950 border border-rose-500/50 rounded-2xl max-w-md w-full p-6 space-y-4 shadow-2xl relative text-white text-xs">
            
            <button
              onClick={() => setShowCreateModal(false)}
              className="absolute right-5 top-5 p-1.5 rounded-lg text-zinc-400 hover:text-white bg-zinc-900 border border-zinc-800"
            >
              <X className="w-4 h-4" />
            </button>

            <h3 className="text-base font-bold text-white flex items-center gap-2 font-mono">
              <ShieldAlert className="w-4 h-4 text-rose-400" />
              <span>Create New Incident Case</span>
            </h3>

            <form onSubmit={handleCreateIncident} className="space-y-3 font-sans">
              <div>
                <label className="block text-zinc-400 mb-1 font-mono">Incident Title</label>
                <input
                  type="text"
                  required
                  value={newTitle}
                  onChange={(e) => setNewTitle(e.target.value)}
                  placeholder="e.g. Lateral Movement Attempt on Core DB"
                  className="w-full bg-black border border-zinc-800 rounded-lg px-3 py-2 text-white font-mono focus:outline-none focus:border-rose-500"
                />
              </div>

              <div>
                <label className="block text-zinc-400 mb-1 font-mono">Incident Summary</label>
                <textarea
                  rows={3}
                  required
                  value={newSummary}
                  onChange={(e) => setNewSummary(e.target.value)}
                  placeholder="Summary of threat event..."
                  className="w-full bg-black border border-zinc-800 rounded-lg p-3 font-mono text-xs text-white focus:outline-none focus:border-rose-500"
                />
              </div>

              <div>
                <label className="block text-zinc-400 mb-1 font-mono">Severity Level</label>
                <select
                  value={newSeverity}
                  onChange={(e) => setNewSeverity(e.target.value)}
                  className="w-full bg-black border border-zinc-800 rounded-lg px-3 py-2 text-white font-mono focus:outline-none focus:border-rose-500"
                >
                  <option value="CRITICAL">CRITICAL (P1 SLA 15m)</option>
                  <option value="HIGH">HIGH (P2 SLA 30m)</option>
                  <option value="MEDIUM">MEDIUM (P3 SLA 2h)</option>
                  <option value="LOW">LOW (P4 SLA 24h)</option>
                </select>
              </div>

              <div>
                <label className="block text-zinc-400 mb-1 font-mono">Assign Lead Analyst</label>
                <input
                  type="text"
                  value={newAnalyst}
                  onChange={(e) => setNewAnalyst(e.target.value)}
                  className="w-full bg-black border border-zinc-800 rounded-lg px-3 py-2 text-white font-mono focus:outline-none focus:border-rose-500"
                />
              </div>

              <div className="pt-2 flex items-center justify-end gap-2 font-mono">
                <button
                  type="button"
                  onClick={() => setShowCreateModal(false)}
                  className="px-4 py-2 rounded-lg bg-zinc-900 border border-zinc-800 text-zinc-300 hover:text-white"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  className="px-4 py-2 rounded-lg bg-rose-600 hover:bg-rose-500 text-white font-bold shadow-md"
                >
                  Create Incident
                </button>
              </div>
            </form>
          </div>
        </div>
      )}

      {/* Close Incident Modal */}
      {showCloseModal && (
        <div className="fixed inset-0 bg-black/80 backdrop-blur-sm z-50 flex items-center justify-center p-4">
          <div className="bg-zinc-950 border border-emerald-500/50 rounded-2xl max-w-md w-full p-6 space-y-4 shadow-2xl relative text-white text-xs">
            
            <button
              onClick={() => setShowCloseModal(false)}
              className="absolute right-5 top-5 p-1.5 rounded-lg text-zinc-400 hover:text-white bg-zinc-900 border border-zinc-800"
            >
              <X className="w-4 h-4" />
            </button>

            <h3 className="text-base font-bold text-white flex items-center gap-2 font-mono">
              <CheckCircle2 className="w-4 h-4 text-emerald-400" />
              <span>Resolve &amp; Close Incident</span>
            </h3>

            <form onSubmit={handleCloseIncident} className="space-y-3 font-sans">
              <div>
                <label className="block text-zinc-400 mb-1 font-mono">Resolution &amp; Lessons Learned Notes</label>
                <textarea
                  rows={4}
                  required
                  value={resolutionNotes}
                  onChange={(e) => setResolutionNotes(e.target.value)}
                  placeholder="Provide resolution details, containment actions taken, and root cause mitigation..."
                  className="w-full bg-black border border-zinc-800 rounded-lg p-3 font-mono text-xs text-white focus:outline-none focus:border-emerald-500"
                />
              </div>

              <div className="pt-2 flex items-center justify-end gap-2 font-mono">
                <button
                  type="button"
                  onClick={() => setShowCloseModal(false)}
                  className="px-4 py-2 rounded-lg bg-zinc-900 border border-zinc-800 text-zinc-300 hover:text-white"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  className="px-4 py-2 rounded-lg bg-emerald-600 hover:bg-emerald-500 text-black font-bold shadow-md"
                >
                  Confirm Closure
                </button>
              </div>
            </form>
          </div>
        </div>
      )}

    </div>
  );
}
