apiVersion: v1
kind: Secret
metadata:
  name: {{ include "netsentinel-x.fullname" . }}-secret
  labels:
    app.kubernetes.io/name: {{ include "netsentinel-x.name" . }}
type: Opaque
stringData:
  JWT_SECRET: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
  DB_PASSWORD: "SuperSecureK8sPassword2026!"
